### ISSUE TITLE
YUV转RGB颜色失真

### ISSUE THREAD

**Issue by PeOS-China** [bookzhan/YUVRenderScript#1]
1、在Camera2Activity中onImageAvailable，u和v数据错位了：
                if (null == yBuffer) {
                    yBuffer = new byte[width * height];
                }
                if (null == uBuffer) {
                    uBuffer = new byte[planes[1].getBuffer().capacity()];
                }
                if (null == vBuffer) {
                    vBuffer = new byte[planes[2].getBuffer().capacity()];
                }
                planes[0].getBuffer().get(yBuffer);
                planes[1].getBuffer().get(vBuffer);
                planes[2].getBuffer().get(uBuffer);
2、在YuvConvertUtil的convertYuv420中，U，V数据也错位：
        scriptC_yuv.set_mInU(vIn);
        scriptC_yuv.set_mInV(uIn);
3、运行，把YUV420_8888的数据转化为RGB，图片失去颜色变成会灰度图

**Comment by bookzhan** [comment]
我在我手机上试了一下，没有问题，UV两边都颠倒就没有问题的，这个工程就不支持转换成RGB, 只是支持转换成RGBA, 也有可能是你手机上的兼容问题RowStride大小不一样导致的，现阶段不打算做支持了，建议你用这个工程https://www.bzblog.online/wordpress/index.php/2020/05/25/androidlibyuv/ 效果性能更好

**Comment by PeOS-China** [comment]
> 我在我手机上试了一下，没有问题，UV两边都颠倒就没有问题的，这个工程就不支持转换成RGB, 只是支持转换成RGBA, 也有可能是你手机上的兼容问题RowStride大小不一样导致的，现阶段不打算做支持了，建议你用这个工程https://www.bzblog.online/wordpress/index.php/2020/05/25/androidlibyuv/ 效果性能更好

谢谢
